### ISSUE TITLE
YAML warning, Loader required

### ISSUE THREAD

**Issue by marshallward** [aidanheerdegen/yamanifest#8]
I'm getting this warning with Python 3.5:
```
/ncrc/home2/Marshall.Ward/.local/lib/python3.5/site-packages/yamanifest/manifest.py:99: YAMLLoadWarning: calling yaml.load_all() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.header, self.data = yaml.load_all(file)
```
looks like an easy fix, but I've never touched this module so might be easier for you to fix.

**Comment by aidanheerdegen** [comment]
I think I fixed it already

https://github.com/aidanheerdegen/yamanifest/blob/master/yamanifest/manifest.py#L99

https://github.com/aidanheerdegen/yamanifest/pull/7

Are you using an old version?

**Comment by marshallward** [comment]
Yeah, you are right, mine must be old.  Shows me for not searching first!

**Comment by marshallward** [comment]
Ah.. well let me re-open.  I am dependent on the PyPI version at the moment.  Has that been updated?

**Comment by aidanheerdegen** [comment]
Heh. I wondered if that was the problem. Probably not. I mostly use `conda` these days. I can update.

**Comment by aidanheerdegen** [comment]
Ok, pypi has been updated to 0.3.8

**Comment by aidanheerdegen** [comment]
I'll add PyPi deployment to Travis or CircleCI.

**Comment by marshallward** [comment]
Beautiful, no more warning, thank you!
